<a href="https://colab.research.google.com/github/hasini0306/AIAC/blob/main/lab_ass(3_3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Task Description#1
• Try 3 different prompts to generate a factorial function.
Expected Output#1
• Comparison of AI-generated code styles

**Explanation for the first prompt:**

Prompt: "Generate a Python function to calculate the factorial of a number."

This prompt is general and doesn't specify a particular method. The generated code uses an iterative approach with a `for` loop to calculate the factorial.

- The function `factorial_prompt_1(n)` takes an integer `n` as input.
- It handles the base case where `n` is 0, returning 1.
- For `n > 0`, it initializes `result` to 1 and then iterates from 1 to `n`, multiplying `result` by each number in the range.
- Finally, it returns the calculated `result`.

**Explanation for the second prompt:**

Prompt: "Write a recursive Python function for factorial calculation."

This prompt specifically asks for a recursive function. The generated code defines a function that calls itself with a smaller input until it reaches the base case.

- The function `factorial_prompt_2(n)` takes an integer `n` as input.
- It handles the base case where `n` is 0, returning 1.
- For `n > 0`, it returns the product of `n` and the result of calling itself with `n-1`. This recursive call continues until `n` becomes 0.

**Explanation for the third prompt:**

Prompt: "Provide a Python function for factorial using a math library."

This prompt requests the use of a specific library for factorial calculation. The generated code imports the `math` module and uses its built-in `factorial` function.

- It imports the `math` module.
- The function `factorial_prompt_3(n)` takes an integer `n` as input.
- It includes a basic check for negative numbers, as the factorial is not defined for them.
- For non-negative numbers, it directly calls `math.factorial(n)` to get the result.

In [ ]:
Task Description#2
• Provide a clear example input-output prompt to generate a sorting function.
Expected Output#2
• Functional sorting code from AI

Here is an example input-output prompt to generate a sorting function:

**Prompt:**

Write a Python function called `sort_list` that takes a list of numbers as input and returns a new list with the numbers sorted in ascending order.

Example Input:
`[3, 1, 4, 1, 5, 9, 2, 6]`

Example Output:
`[1, 1, 2, 3, 4, 5, 6, 9]`

In [1]:
def sort_list(numbers):
  """Sorts a list of numbers in ascending order."""
  return sorted(numbers)

# Example usage:
input_list = [3, 1, 4, 1, 5, 9, 2, 6]
sorted_result = sort_list(input_list)
print(sorted_result)

[1, 1, 2, 3, 4, 5, 6, 9]


**Explanation of the sorting function:**

The generated code defines a Python function called `sort_list` that takes a list of numbers as input and returns a new list with the numbers sorted in ascending order.

- The function `sort_list(numbers)` takes a list `numbers` as input.
- It uses the built-in Python function `sorted()` to sort the input list in ascending order.
- The `sorted()` function returns a new sorted list, leaving the original list unchanged.
- The function then returns this new sorted list.

The example usage demonstrates how to call the `sort_list` function with an example list and prints the returned sorted list.

In [ ]:
Task Description#3
• Start with the vague prompt “Generate python code to calculate power bill” and
improve it step-by-step
Expected Output#3
• Enhanced AI output with clearer prompts

# Task
Start with the vague prompt “Generate python code to calculate power bill” and improve it step-by-step and explain it

## Start with a vague prompt

### Subtask:
Use the prompt "Generate python code to calculate power bill" and generate the initial code.


**Reasoning**:
The subtask requires generating Python code based on a vague prompt about calculating a power bill. I will create a code cell with the prompt as a comment and write some basic code that attempts to address the prompt, acknowledging its vagueness.



In [2]:
# Generate python code to calculate power bill

# Due to the vagueness of the prompt, this is a very basic example.
# A real power bill calculation would require much more information (e.g., tiered rates, taxes, fees).

def calculate_power_bill(kwh_consumed, rate_per_kwh):
  """Calculates a simple power bill based on kWh consumed and rate per kWh."""
  return kwh_consumed * rate_per_kwh

# Example usage with assumed values:
kilowatt_hours = 500  # Example consumption
cost_per_kwh = 0.15   # Example rate in currency per kWh

bill_amount = calculate_power_bill(kilowatt_hours, cost_per_kwh)
print(f"Estimated power bill: ${bill_amount:.2f}")

Estimated power bill: $75.00


## Explain the initial code

### Subtask:
Describe what the initial code does and its limitations based on the vague prompt.


**Reasoning**:
Describe what the initial code does and its limitations based on the vague prompt.



In [3]:
# Explanation of the initial code and its limitations

print("Explanation of the initial power bill calculation code:")
print("The initial code defines a function `calculate_power_bill` that takes two arguments:")
print("- `kwh_consumed`: The total kilowatt-hours consumed.")
print("- `rate_per_kwh`: The cost per kilowatt-hour.")
print("It calculates the power bill by simply multiplying the `kwh_consumed` by the `rate_per_kwh`.")
print("This is a very basic linear calculation.")

print("\nLimitations of the initial code due to the vague prompt:")
print("The vague prompt 'Generate python code to calculate power bill' led to a very simplistic model that does not account for common complexities in real-world power bills, such as:")
print("- **Tiered Rates:** Power companies often charge different rates for different consumption levels (e.g., the first 100 kWh at one rate, the next 200 kWh at a higher rate).")
print("- **Fixed Charges:** Many bills include fixed monthly service fees regardless of consumption.")
print("- **Taxes and Surcharges:** Various taxes, regulatory fees, and surcharges are typically added to the usage cost.")
print("- **Time-of-Use Rates:** Rates can vary depending on the time of day (peak vs. off-peak hours).")
print("- **Discounts or Rebates:** Some customers might be eligible for discounts or rebates.")
print("The current code only considers a single, constant rate and does not include any of these additional factors.")

Explanation of the initial power bill calculation code:
The initial code defines a function `calculate_power_bill` that takes two arguments:
- `kwh_consumed`: The total kilowatt-hours consumed.
- `rate_per_kwh`: The cost per kilowatt-hour.
It calculates the power bill by simply multiplying the `kwh_consumed` by the `rate_per_kwh`.
This is a very basic linear calculation.

Limitations of the initial code due to the vague prompt:
The vague prompt 'Generate python code to calculate power bill' led to a very simplistic model that does not account for common complexities in real-world power bills, such as:
- **Tiered Rates:** Power companies often charge different rates for different consumption levels (e.g., the first 100 kWh at one rate, the next 200 kWh at a higher rate).
- **Fixed Charges:** Many bills include fixed monthly service fees regardless of consumption.
- **Taxes and Surcharges:** Various taxes, regulatory fees, and surcharges are typically added to the usage cost.
- **Time-of

## Refine the prompt (step 1)

### Subtask:
Based on the limitations of the initial code, refine the prompt to be more specific (e.g., specify input details like usage in kWh and cost per kWh). Generate new code based on the refined prompt.


**Reasoning**:
Formulate a more specific prompt and generate the corresponding Python code to calculate a power bill, including specific inputs like kWh consumed and cost per kWh.



In [4]:
# Refined Prompt:
# Generate Python code for a function that calculates a power bill.
# The function should take two arguments: the total kilowatt-hours (kWh) consumed and the cost per kilowatt-hour (rate).
# It should return the total bill amount by multiplying the kWh consumed by the rate.

def calculate_power_bill_refined(kwh_consumed, rate_per_kwh):
  """Calculates a power bill based on kWh consumed and a fixed rate per kWh.

  Args:
    kwh_consumed: The total kilowatt-hours consumed (float or int).
    rate_per_kwh: The cost per kilowatt-hour (float).

  Returns:
    The total bill amount (float).
  """
  if kwh_consumed < 0 or rate_per_kwh < 0:
      print("Warning: kWh consumed and rate per kWh should be non-negative.")
      return 0
  return kwh_consumed * rate_per_kwh

# Example usage with specific inputs:
kilowatt_hours_example = 750
cost_per_kwh_example = 0.18

bill_amount_refined = calculate_power_bill_refined(kilowatt_hours_example, cost_per_kwh_example)
print(f"Estimated power bill (refined): ${bill_amount_refined:.2f}")

Estimated power bill (refined): $135.00


## Explain the improved code (step 1)

### Subtask:
Explain how the refined prompt led to better code and describe the functionality of the new code.


**Reasoning**:
Describe how the refined prompt improved the code and explain the functionality of the new code, addressing the initial prompt's vagueness, the impact of the first refined prompt, and the details of the `calculate_power_bill_refined` function including its inputs, calculation, and basic validation.



In [5]:
# Explanation of how the refined prompt led to better code and the functionality of the new code.

print("Explanation of the refined power bill calculation code:")

print("\n1. Initial Prompt Vagueness:")
print("The initial prompt, 'Generate python code to calculate power bill', was very vague.")
print("This vagueness resulted in code that could only perform the most basic calculation: a simple multiplication of assumed total consumption by an assumed fixed rate.")
print("It lacked any detail about what inputs were available or what specific calculation method was desired.")

print("\n2. Impact of the First Refined Prompt:")
print("The first refined prompt provided crucial specific details:")
print("- It explicitly stated the required inputs: 'total kilowatt-hours (kWh) consumed' and 'cost per kilowatt-hour (rate)'.")
print("- It specified the desired calculation: 'return the total bill amount by multiplying the kWh consumed by the rate'.")
print("This increased specificity directly led to the generation of the `calculate_power_bill_refined` function, which is tailored to these inputs and calculation.")

print("\n3. Functionality of `calculate_power_bill_refined`:")
print("The `calculate_power_bill_refined` function is designed to calculate a power bill based on a fixed rate.")
print("It takes two inputs:")
print("  - `kwh_consumed`: Represents the total amount of electricity consumed in kilowatt-hours.")
print("  - `rate_per_kwh`: Represents the fixed cost charged for each kilowatt-hour consumed.")
print("The function calculates the total bill amount by simply multiplying `kwh_consumed` by `rate_per_kwh`.")

print("\n4. Basic Input Validation:")
print("An improvement in the refined code is the addition of basic input validation.")
print("It checks if either `kwh_consumed` or `rate_per_kwh` is negative.")
print("If a negative value is detected, it prints a warning message and returns 0.")
print("While simple, this adds a layer of robustness compared to the initial version, as power consumption and rates are typically non-negative.")

print("\n5. Improvement over Initial Version:")
print("The refined code is an improvement because the clearer prompt led to a function that is more directly usable for a specific, albeit still basic, power bill scenario.")
print("It correctly implements the calculation method requested by the refined prompt and includes a basic check for invalid inputs.")
print("However, it's important to note that this refined code still represents a basic scenario and does not account for complexities like tiered rates, taxes, or fixed fees, which would require further prompt refinement.")

Explanation of the refined power bill calculation code:

1. Initial Prompt Vagueness:
The initial prompt, 'Generate python code to calculate power bill', was very vague.
This vagueness resulted in code that could only perform the most basic calculation: a simple multiplication of assumed total consumption by an assumed fixed rate.
It lacked any detail about what inputs were available or what specific calculation method was desired.

2. Impact of the First Refined Prompt:
The first refined prompt provided crucial specific details:
- It explicitly stated the required inputs: 'total kilowatt-hours (kWh) consumed' and 'cost per kilowatt-hour (rate)'.
- It specified the desired calculation: 'return the total bill amount by multiplying the kWh consumed by the rate'.
This increased specificity directly led to the generation of the `calculate_power_bill_refined` function, which is tailored to these inputs and calculation.

3. Functionality of `calculate_power_bill_refined`:
The `calculate_powe

## Refine the prompt (step 2)

### Subtask:
Further refine the prompt to include more details (e.g., different billing tiers, fixed charges). Generate new code based on this more specific prompt.


**Reasoning**:
Write a more detailed prompt and generate the Python code for calculating a power bill with tiered rates and a fixed charge based on the refined prompt. Include example usage.



In [6]:
# Refined Prompt (incorporating tiered rates and fixed charges):
# Generate Python code for a function that calculates a power bill.
# The function should take the total kilowatt-hours (kWh) consumed as input.
# The calculation should include:
# 1. A fixed monthly service charge.
# 2. Tiered rates for energy consumption:
#    - A lower rate for the first X kWh consumed.
#    - A higher rate for any kWh consumed above X.
# Provide example usage demonstrating consumption that falls into both tiers.

def calculate_power_bill_tiered(kwh_consumed, fixed_charge, tier1_limit, tier1_rate, tier2_rate):
    """Calculates a power bill with a fixed charge and tiered rates.

    Args:
        kwh_consumed: The total kilowatt-hours consumed (float or int).
        fixed_charge: The fixed monthly service charge (float).
        tier1_limit: The upper limit for the first tier in kWh (float or int).
        tier1_rate: The rate per kWh for consumption up to tier1_limit (float).
        tier2_rate: The rate per kWh for consumption above tier1_limit (float).

    Returns:
        The total bill amount (float).
    """
    if kwh_consumed < 0 or fixed_charge < 0 or tier1_limit < 0 or tier1_rate < 0 or tier2_rate < 0:
        print("Warning: Inputs should be non-negative.")
        return 0.0

    bill_amount = fixed_charge

    if kwh_consumed <= tier1_limit:
        bill_amount += kwh_consumed * tier1_rate
    else:
        bill_amount += tier1_limit * tier1_rate
        bill_amount += (kwh_consumed - tier1_limit) * tier2_rate

    return bill_amount

# Example usage with specific inputs and consumption crossing the tier threshold:
fixed_monthly_charge = 20.00  # Example fixed charge
tier_1_kwh_limit = 300        # Example limit for the first tier
rate_tier_1 = 0.12            # Example rate for the first tier ($/kWh)
rate_tier_2 = 0.18            # Example rate for the second tier ($/kWh)

# Consumption that falls into both tiers
example_kwh_consumption = 450

total_bill = calculate_power_bill_tiered(
    example_kwh_consumption,
    fixed_monthly_charge,
    tier_1_kwh_limit,
    rate_tier_1,
    rate_tier_2
)

print(f"Consumption: {example_kwh_consumption} kWh")
print(f"Fixed Charge: ${fixed_monthly_charge:.2f}")
print(f"Tier 1 Limit: {tier_1_kwh_limit} kWh @ ${rate_tier_1:.2f}/kWh")
print(f"Tier 2 Rate: ${rate_tier_2:.2f}/kWh")
print(f"Total Power Bill (tiered): ${total_bill:.2f}")

# Example usage with consumption only in the first tier
example_kwh_consumption_tier1_only = 200
total_bill_tier1_only = calculate_power_bill_tiered(
    example_kwh_consumption_tier1_only,
    fixed_monthly_charge,
    tier_1_kwh_limit,
    rate_tier_1,
    rate_tier_2
)
print(f"\nConsumption: {example_kwh_consumption_tier1_only} kWh")
print(f"Total Power Bill (tiered, tier 1 only): ${total_bill_tier1_only:.2f}")

Consumption: 450 kWh
Fixed Charge: $20.00
Tier 1 Limit: 300 kWh @ $0.12/kWh
Tier 2 Rate: $0.18/kWh
Total Power Bill (tiered): $83.00

Consumption: 200 kWh
Total Power Bill (tiered, tier 1 only): $44.00


**Reasoning**:
Explain how the further refined prompt led to the improved code, describing the functionality of the new code that includes tiered rates and a fixed charge.



In [7]:
# Explanation of how the further refined prompt led to better code and the functionality of the new code.

print("Explanation of the further refined power bill calculation code:")

print("\n1. Impact of the Second Refined Prompt:")
print("The second refined prompt built upon the first by adding more real-world complexities:")
print("- It explicitly required the inclusion of a 'fixed monthly service charge'.")
print("- Crucially, it introduced 'tiered rates', specifying a 'lower rate for the first X kWh' and a 'higher rate for any kWh consumed above X'.")
print("- It also requested example usage that demonstrates 'consumption that falls into both tiers'.")
print("This significantly increased specificity guided the AI to generate a function capable of handling these distinct billing components.")

print("\n2. Functionality of `calculate_power_bill_tiered`:")
print("The `calculate_power_bill_tiered` function is designed to calculate a power bill based on a fixed charge and a two-tier consumption rate structure.")
print("It takes five inputs:")
print("  - `kwh_consumed`: The total amount of electricity consumed.")
print("  - `fixed_charge`: A flat fee applied regardless of consumption.")
print("  - `tier1_limit`: The threshold in kWh where the rate changes.")
print("  - `tier1_rate`: The cost per kWh for consumption up to `tier1_limit`.")
print("  - `tier2_rate`: The cost per kWh for consumption exceeding `tier1_limit`.")

print("\n3. Calculation Logic:")
print("The function calculates the bill as follows:")
print("  - It starts by adding the `fixed_charge` to the total bill.")
print("  - It then checks if `kwh_consumed` is less than or equal to the `tier1_limit`:")
print("    - If true, the entire consumption is billed at the `tier1_rate` (`kwh_consumed * tier1_rate`).")
print("    - If false (consumption is above the limit), it calculates the cost for the first tier (`tier1_limit * tier1_rate`) and adds it.")
print("    - It then calculates the remaining consumption that falls into the second tier (`kwh_consumed - tier1_limit`) and bills it at the `tier2_rate`, adding this amount to the total.")

print("\n4. Input Validation:")
print("Similar to the previous version, basic validation is included to check for negative input values, printing a warning and returning 0.0 if found.")

print("\n5. Improvement over Previous Version:")
print("This version is a significant improvement because the prompt explicitly requested and the code successfully implemented common real-world billing complexities: fixed charges and tiered rates.")
print("It moves beyond a simple linear calculation to a more realistic model, demonstrating how increasingly specific prompts lead to more sophisticated and accurate code outputs for complex tasks.")
print("The inclusion of example usage covering both tier scenarios further validates the function's logic.")

Explanation of the further refined power bill calculation code:

1. Impact of the Second Refined Prompt:
The second refined prompt built upon the first by adding more real-world complexities:
- It explicitly required the inclusion of a 'fixed monthly service charge'.
- Crucially, it introduced 'tiered rates', specifying a 'lower rate for the first X kWh' and a 'higher rate for any kWh consumed above X'.
- It also requested example usage that demonstrates 'consumption that falls into both tiers'.
This significantly increased specificity guided the AI to generate a function capable of handling these distinct billing components.

2. Functionality of `calculate_power_bill_tiered`:
The `calculate_power_bill_tiered` function is designed to calculate a power bill based on a fixed charge and a two-tier consumption rate structure.
It takes five inputs:
  - `kwh_consumed`: The total amount of electricity consumed.
  - `fixed_charge`: A flat fee applied regardless of consumption.
  - `tier1_limit

## Explain the improved code (step 2)

### Subtask:
Explain the functionality of the code generated from the second refined prompt and how it addresses more complex scenarios.


**Reasoning**:
Explain the functionality of the code generated from the second refined prompt, detailing its inputs, calculation logic, validation, and improvements over the previous versions, as per the instructions.



In [8]:
# Explanation of the functionality of the code generated from the second refined prompt
# and how it addresses more complex scenarios.

print("Explanation of the functionality of the `calculate_power_bill_tiered` function:")

print("\n1. Addressing Complex Scenarios:")
print("The second refined prompt, by specifically requesting the inclusion of fixed charges and tiered rates, allowed the AI to generate code that models a more complex and realistic power billing scenario compared to the single-rate calculations in previous steps.")
print("Real-world power bills frequently include these elements, making this function significantly more practical.")

print("\n2. Inputs of the `calculate_power_bill_tiered` function:")
print("This function requires five specific inputs to perform the tiered calculation:")
print("  - `kwh_consumed`: The total electricity consumed by the customer in kilowatt-hours.")
print("  - `fixed_charge`: A flat fee that is charged each billing period regardless of the amount of electricity consumed.")
print("  - `tier1_limit`: The upper threshold of consumption (in kWh) for the first billing tier.")
print("  - `tier1_rate`: The cost per kilowatt-hour for all consumption up to the `tier1_limit`.")
print("  - `tier2_rate`: The cost per kilowatt-hour for all consumption exceeding the `tier1_limit`.")

print("\n3. Step-by-Step Calculation Logic:")
print("The function calculates the total power bill using the following logic:")
print("  - It initializes the `bill_amount` with the `fixed_charge` as this is a base cost.")
print("  - It then checks if the `kwh_consumed` is less than or equal to the `tier1_limit`.")
print("    - If true, it means all consumption falls within the first tier. The cost for consumption is calculated by multiplying `kwh_consumed` by `tier1_rate`, and this amount is added to the `bill_amount`.")
print("    - If false, it means consumption crosses into the second tier. The cost for the first tier is calculated by multiplying `tier1_limit` by `tier1_rate` and added to the `bill_amount`. The remaining consumption (`kwh_consumed - tier1_limit`) is then calculated and billed at the `tier2_rate`, and this additional amount is also added to the `bill_amount`.")
print("  - Finally, the function returns the calculated `bill_amount` which includes the fixed charge and the consumption charges based on the applicable tier(s).")

print("\n4. Input Validation:")
print("The code includes basic input validation at the beginning of the function.")
print("It checks if any of the input values (`kwh_consumed`, `fixed_charge`, `tier1_limit`, `tier1_rate`, `tier2_rate`) are negative.")
print("If any negative value is detected, it prints a warning message to the console and returns `0.0`, as these values are typically non-negative in a real-world scenario.")

print("\n5. Summary of Improvements:")
print("The `calculate_power_bill_tiered` function is a significant improvement over the simpler, single-rate calculation code from the previous step.")
print("  - It accurately reflects real-world power billing scenarios by incorporating both a fixed monthly charge and a tiered rate structure.")
print("  - It correctly handles consumption that falls entirely within the first tier and consumption that crosses into the second tier, applying the appropriate rates.")
print("  - The increased complexity in the prompt directly resulted in a more sophisticated and accurate code implementation.")
print("This demonstrates the principle that more detailed and specific prompts lead to AI-generated code that can handle more intricate tasks and better model real-world systems.")

Explanation of the functionality of the `calculate_power_bill_tiered` function:

1. Addressing Complex Scenarios:
The second refined prompt, by specifically requesting the inclusion of fixed charges and tiered rates, allowed the AI to generate code that models a more complex and realistic power billing scenario compared to the single-rate calculations in previous steps.
Real-world power bills frequently include these elements, making this function significantly more practical.

2. Inputs of the `calculate_power_bill_tiered` function:
This function requires five specific inputs to perform the tiered calculation:
  - `kwh_consumed`: The total electricity consumed by the customer in kilowatt-hours.
  - `fixed_charge`: A flat fee that is charged each billing period regardless of the amount of electricity consumed.
  - `tier1_limit`: The upper threshold of consumption (in kWh) for the first billing tier.
  - `tier1_rate`: The cost per kilowatt-hour for all consumption up to the `tier1_limit

## Summary:

### Data Analysis Key Findings

*   The initial vague prompt "Generate python code to calculate power bill" resulted in a very basic linear calculation (`kwh_consumed * rate_per_kwh`) that did not account for common complexities like tiered rates, fixed charges, taxes, or time-of-use rates.
*   Refining the prompt to specifically include inputs like total kWh consumed and cost per kWh led to code that performed a more directed single-rate calculation and added basic input validation for non-negative values.
*   Further refining the prompt to include details about a fixed monthly service charge and a two-tier rate structure resulted in a more sophisticated function (`calculate_power_bill_tiered`) that accurately calculates bills by adding the fixed charge and applying different rates based on consumption thresholds.
*   The tiered calculation logic correctly handles scenarios where consumption is within the first tier and where it crosses into the second tier, as demonstrated by example calculations (e.g., 450 kWh resulting in a bill of \$83.00 and 200 kWh resulting in a bill of \$44.00 with specified rates and fixed charge).

### Insights or Next Steps

*   Incrementally adding specific details to a prompt significantly improves the relevance and complexity of the generated code, moving from a simplistic model to one that incorporates more real-world billing factors like fixed charges and tiered rates.
*   Future refinements could include handling additional complexities such as multiple tiers, taxes, surcharges, or time-of-use rates to build a more comprehensive power bill calculation model.


In [ ]:
Task Description#4
• Write structured comments to help AI generate two linked functions (e.g., login_user()
and register_user()).
Expected Output#4
• Consistent functions with shared logic

In [9]:
# Task: Generate two linked Python functions: register_user and login_user.
# The functions should interact with a simple in-memory 'database' (a dictionary).
#
# Function 1: register_user
# Description: Registers a new user in the database.
# Inputs: username (string), password (string), database (dictionary)
# Behavior:
# - Check if the username already exists in the database.
# - If the username exists, print a message and return False.
# - If the username does not exist, add the username and password (you can store the password as is for this example, or hash it for better practice) to the database.
# - Print a success message and return True.
#
# Function 2: login_user
# Description: Logs in an existing user.
# Inputs: username (string), password (string), database (dictionary)
# Behavior:
# - Check if the username exists in the database.
# - If the username does not exist, print a message and return False.
# - If the username exists, check if the provided password matches the stored password.
# - If the password matches, print a success message and return True.
# - If the password does not match, print an error message and return False.

# Simple in-memory database
user_database = {}

def register_user(username, password, database):
    """Registers a new user in the database."""
    if username in database:
        print(f"Username '{username}' already exists.")
        return False
    else:
        database[username] = password # In a real application, hash the password
        print(f"User '{username}' registered successfully.")
        return True

def login_user(username, password, database):
    """Logs in an existing user."""
    if username not in database:
        print(f"Username '{username}' not found.")
        return False
    else:
        if database[username] == password:
            print(f"User '{username}' logged in successfully.")
            return True
        else:
            print("Incorrect password.")
            return False

# Example Usage:
print("Attempting to register 'test_user'...")
register_user("test_user", "password123", user_database)

print("\nAttempting to register 'test_user' again...")
register_user("test_user", "another_password", user_database)

print("\nAttempting to login 'test_user' with correct password...")
login_user("test_user", "password123", user_database)

print("\nAttempting to login 'test_user' with incorrect password...")
login_user("test_user", "wrong_password", user_database)

print("\nAttempting to login 'non_existent_user'...")
login_user("non_existent_user", "any_password", user_database)

print("\nCurrent database state:", user_database)

Attempting to register 'test_user'...
User 'test_user' registered successfully.

Attempting to register 'test_user' again...
Username 'test_user' already exists.

Attempting to login 'test_user' with correct password...
User 'test_user' logged in successfully.

Attempting to login 'test_user' with incorrect password...
Incorrect password.

Attempting to login 'non_existent_user'...
Username 'non_existent_user' not found.

Current database state: {'test_user': 'password123'}


**Explanation of the `register_user` and `login_user` functions:**

The code defines two Python functions, `register_user` and `login_user`, that interact with a simple in-memory dictionary acting as a user database. Structured comments were used to guide the generation of these functions.

**1. `register_user(username, password, database)`**

- **Purpose:** To add a new user to the `database`.
- **Inputs:** Takes a `username` (string), a `password` (string), and the `database` (dictionary).
- **Functionality:**
    - It first checks if the provided `username` already exists as a key in the `database`.
    - If the `username` is found, it prints a message indicating the user already exists and returns `False`.
    - If the `username` is not found, it adds the `username` as a key to the `database` with the `password` as its corresponding value. A success message is printed, and the function returns `True`.
    - **Note:** In a real-world application, the password should be securely hashed before storing it, rather than stored in plain text as in this example.

**2. `login_user(username, password, database)`**

- **Purpose:** To verify the credentials of an existing user.
- **Inputs:** Takes a `username` (string), a `password` (string), and the `database` (dictionary).
- **Functionality:**
    - It first checks if the provided `username` exists as a key in the `database`.
    - If the `username` is not found, it prints a message indicating the user was not found and returns `False`.
    - If the `username` is found, it then compares the provided `password` with the password stored in the `database` for that `username`.
    - If the passwords match, a successful login message is printed, and the function returns `True`.
    - If the passwords do not match, an incorrect password message is printed, and the function returns `False`.

**Shared Logic/Interaction:**

- Both functions operate on the same `user_database` dictionary, demonstrating how they are linked.
- `register_user` modifies the database by adding new entries.
- `login_user` queries the database to check for existing users and verify passwords.
- The structured comments clearly defined the inputs, behavior, and purpose of each function, leading to the generation of consistent and interacting code.

The example usage demonstrates the workflow of registering a user, attempting to re-register the same user, and then attempting to log in with correct and incorrect credentials, as well as attempting to log in with a non-existent user. The final print statement shows the state of the `user_database` after these operations.

In [ ]:
Task Description#5
• Analyzing Prompt Specificity: Improving Temperature Conversion Function with
Clear Instructions
Expected Output#5
• Code quality difference analysis for various prompts

# Task
Analyze how prompt specificity affects the generation of a Python temperature conversion function by starting with a vague prompt, progressively refining it, and explaining the resulting code at each step.

## Start with a vague prompt

### Subtask:
Use a vague prompt like "Generate a Python function for temperature conversion" and generate the initial code.


**Reasoning**:
The subtask requires generating Python code based on a vague prompt about temperature conversion. I will create a code cell with the prompt as a comment and write a basic function that assumes a common conversion, like Celsius to Fahrenheit, due to the prompt's vagueness.



In [10]:
# Generate a Python function for temperature conversion

# Due to the vagueness of the prompt, this function assumes Celsius to Fahrenheit conversion.
def convert_temperature(temp_celsius):
  """Converts temperature from Celsius to Fahrenheit."""
  return (temp_celsius * 9/5) + 32

# Example usage with an assumed Celsius value:
celsius_temp = 25
fahrenheit_temp = convert_temperature(celsius_temp)
print(f"{celsius_temp}°C is equal to {fahrenheit_temp}°F")

25°C is equal to 77.0°F


## Explain the initial code

### Subtask:
Describe what the initial code does, what conversion it assumes (e.g., Celsius to Fahrenheit), and its limitations due to the vague prompt (e.g., only handles one type of conversion, no input validation).


**Reasoning**:
Describe what the initial code does, what conversion it assumes (e.g., Celsius to Fahrenheit), and its limitations due to the vague prompt (e.g., only handles one type of conversion, no input validation).



In [11]:
# Explanation of the initial temperature conversion code and its limitations

print("Explanation of the initial temperature conversion code:")
print("The initial code defines a function `convert_temperature` that takes one argument:")
print("- `temp_celsius`: An assumed temperature value in Celsius.")

print("\nAssumed Conversion:")
print("Based on the vague prompt 'Generate a Python function for temperature conversion', the AI generated code that specifically performs a conversion from **Celsius to Fahrenheit**.")
print("The formula used is the standard formula: (Celsius * 9/5) + 32.")

print("\nLimitations of the initial code due to the vague prompt:")
print("The vague prompt led to several significant limitations in the generated code:")
print("- **Single Conversion Type:** The function only handles Celsius to Fahrenheit conversion. It cannot convert from Fahrenheit to Celsius, Kelvin, or any other temperature scale.")
print("- **No Input Validation:** The code does not include any checks to ensure the input is a valid number or within a reasonable range for temperature. Passing non-numeric input would likely result in an error.")
print("- **Lack of Flexibility:** The function is hardcoded for one specific conversion and cannot be easily adapted to perform other conversions without modifying the function's internal logic.")
print("- **Implicit Input Unit:** The prompt did not specify the input unit, leading the AI to assume Celsius. This ambiguity makes the function less clear and potentially confusing for a user who might expect a different input unit.")
print("In summary, the vagueness of the prompt resulted in a function that is very basic, lacks robustness, and is limited to a single, assumed conversion type.")

Explanation of the initial temperature conversion code:
The initial code defines a function `convert_temperature` that takes one argument:
- `temp_celsius`: An assumed temperature value in Celsius.

Assumed Conversion:
Based on the vague prompt 'Generate a Python function for temperature conversion', the AI generated code that specifically performs a conversion from **Celsius to Fahrenheit**.
The formula used is the standard formula: (Celsius * 9/5) + 32.

Limitations of the initial code due to the vague prompt:
The vague prompt led to several significant limitations in the generated code:
- **Single Conversion Type:** The function only handles Celsius to Fahrenheit conversion. It cannot convert from Fahrenheit to Celsius, Kelvin, or any other temperature scale.
- **No Input Validation:** The code does not include any checks to ensure the input is a valid number or within a reasonable range for temperature. Passing non-numeric input would likely result in an error.
- **Lack of Flexibil

## Refine the prompt (step 1)

### Subtask:
Refine the prompt to specify a particular conversion, for example, "Generate a Python function to convert Celsius to Fahrenheit". Generate new code based on this refined prompt.


**Reasoning**:
Write a markdown cell with the refined prompt as requested.



In [12]:
```markdown
## Refine the prompt (step 1)

### Subtask:
Refine the prompt to specify a particular conversion, for example, "Generate a Python function to convert Celsius to Fahrenheit". Generate new code based on this refined prompt.


SyntaxError: invalid syntax (ipython-input-413993327.py, line 1)

**Reasoning**:
Create a markdown cell with the refined prompt as requested.



In [13]:
# Refined Prompt (specifying Celsius to Fahrenheit):
# Generate a Python function named 'celsius_to_fahrenheit' that takes a temperature in Celsius as input and returns the equivalent temperature in Fahrenheit.

def celsius_to_fahrenheit(celsius):
  """Converts temperature from Celsius to Fahrenheit."""
  # Add basic input validation
  if not isinstance(celsius, (int, float)):
      print("Warning: Input must be a number.")
      return None
  return (celsius * 9/5) + 32

# Example usage:
celsius_temp_example = 30
fahrenheit_result = celsius_to_fahrenheit(celsius_temp_example)

if fahrenheit_result is not None:
    print(f"{celsius_temp_example}°C is equal to {fahrenheit_result}°F")

# Example with non-numeric input
print("\nAttempting conversion with non-numeric input:")
fahrenheit_result_invalid = celsius_to_fahrenheit("twenty")

30°C is equal to 86.0°F

Attempting conversion with non-numeric input:


## Explain the improved code (step 1)

### Subtask:
Explain how the refined prompt resulted in more directed code and describe the functionality of the Celsius to Fahrenheit conversion function, including the formula used.


**Reasoning**:
Explain how the refined prompt resulted in more directed code and describe the functionality of the Celsius to Fahrenheit conversion function, including the formula used.



In [14]:
# Explanation of how the refined prompt led to more directed code and the functionality of the new code.

print("Explanation of the refined temperature conversion code (Celsius to Fahrenheit):")

print("\n1. Impact of the Refined Prompt:")
print("The initial prompt 'Generate a Python function for temperature conversion' was very vague, leading to a default assumption of Celsius to Fahrenheit and a basic function.")
print("The refined prompt 'Generate a Python function named 'celsius_to_fahrenheit' that takes a temperature in Celsius as input and returns the equivalent temperature in Fahrenheit' was much more specific.")
print("This specificity directly instructed the AI on:")
print("- The desired function name (`celsius_to_fahrenheit`).")
print("- The input unit (Celsius).")
print("- The output unit (Fahrenheit).")
print("- The specific conversion required (Celsius to Fahrenheit).")
print("This clear instruction eliminated ambiguity and allowed the AI to generate code precisely tailored to the requested conversion, unlike the initial vague prompt.")

print("\n2. Functionality of `celsius_to_fahrenheit`:")
print("The `celsius_to_fahrenheit` function is designed specifically for converting a temperature value from the Celsius scale to the Fahrenheit scale.")
print("It takes one argument:")
print("  - `celsius`: This is the temperature value that you want to convert, expected to be in degrees Celsius.")

print("\n3. Conversion Formula Used:")
print("The function uses the standard and widely accepted formula for converting Celsius to Fahrenheit:")
print("  Fahrenheit = (Celsius * 9/5) + 32")
print("The code implements this directly: `return (celsius * 9/5) + 32`")

print("\n4. Additional Features (Basic Input Validation):")
print("Although not explicitly requested in the refined prompt, the generated code includes basic input validation.")
print("It checks if the input `celsius` is a numeric type (int or float) using `isinstance(celsius, (int, float))`.")
print("If the input is not a number, it prints a warning message and returns `None`. This makes the function more robust by handling potentially invalid inputs gracefully instead of raising an error.")

print("\n5. Improvement over Initial Version:")
print("This refined code is a significant improvement over the initial vague-prompted version because:")
print("- It performs the *specific* conversion requested by the refined prompt (Celsius to Fahrenheit), removing the ambiguity of the initial assumption.")
print("- It has a clear function name (`celsius_to_fahrenheit`) that indicates its purpose.")
print("- It includes basic input validation, making it more reliable.")
print("This demonstrates how a more specific prompt leads to code that is not only more accurate to the user's intent but can also include helpful features like validation.")

Explanation of the refined temperature conversion code (Celsius to Fahrenheit):

1. Impact of the Refined Prompt:
The initial prompt 'Generate a Python function for temperature conversion' was very vague, leading to a default assumption of Celsius to Fahrenheit and a basic function.
The refined prompt 'Generate a Python function named 'celsius_to_fahrenheit' that takes a temperature in Celsius as input and returns the equivalent temperature in Fahrenheit' was much more specific.
This specificity directly instructed the AI on:
- The desired function name (`celsius_to_fahrenheit`).
- The input unit (Celsius).
- The output unit (Fahrenheit).
- The specific conversion required (Celsius to Fahrenheit).
This clear instruction eliminated ambiguity and allowed the AI to generate code precisely tailored to the requested conversion, unlike the initial vague prompt.

2. Functionality of `celsius_to_fahrenheit`:
The `celsius_to_fahrenheit` function is designed specifically for converting a tempera

## Refine the prompt (step 2)

### Subtask:
Further refine the prompt to include more details, such as handling different units (Celsius, Fahrenheit, Kelvin) and specifying the desired output format or error handling for invalid inputs. Generate new code based on this more specific prompt, potentially creating a function that can handle multiple conversion types.


**Reasoning**:
Define the refined prompt including handling multiple units and error handling, then generate the corresponding Python code for a function that can perform conversions between Celsius, Fahrenheit, and Kelvin with validation, and finally include example usage.



In [15]:
# Refined Prompt (incorporating multiple units and error handling):
# Generate a Python function named 'convert_temperature_advanced'.
# This function should take three arguments:
# 1. The temperature value (numeric).
# 2. The input unit (string: 'Celsius', 'Fahrenheit', or 'Kelvin').
# 3. The desired output unit (string: 'Celsius', 'Fahrenheit', or 'Kelvin').
# The function should perform the requested temperature conversion.
# Include error handling for:
# - Non-numeric temperature input.
# - Invalid input or output unit strings (not 'Celsius', 'Fahrenheit', or 'Kelvin').
# - Return None and print an informative error message in case of any error.
# Provide example usage demonstrating conversions between different units (C to F, F to C, C to K, K to C, F to K, K to F) and examples of invalid inputs.

def convert_temperature_advanced(value, input_unit, output_unit):
    """
    Converts temperature between Celsius, Fahrenheit, and Kelvin with error handling.

    Args:
        value: The temperature value (numeric).
        input_unit: The unit of the input temperature ('Celsius', 'Fahrenheit', 'Kelvin').
        output_unit: The desired unit for the output temperature ('Celsius', 'Fahrenheit', 'Kelvin').

    Returns:
        The converted temperature value (float), or None if an error occurs.
    """
    # 1. Error handling for non-numeric temperature input
    if not isinstance(value, (int, float)):
        print(f"Error: Invalid temperature value '{value}'. Input value must be numeric.")
        return None

    # Normalize units to lowercase for easier comparison (optional but good practice)
    input_unit_lower = input_unit.lower()
    output_unit_lower = output_unit.lower()

    valid_units = ['celsius', 'fahrenheit', 'kelvin']

    # 2. Error handling for invalid input or output unit strings
    if input_unit_lower not in valid_units:
        print(f"Error: Invalid input unit '{input_unit}'. Valid units are: {', '.join(valid_units)}.")
        return None
    if output_unit_lower not in valid_units:
        print(f"Error: Invalid output unit '{output_unit}'. Valid units are: {', '.join(valid_units)}.")
        return None

    # Convert input to Celsius first for easier conversion logic
    if input_unit_lower == 'fahrenheit':
        celsius_value = (value - 32) * 5/9
    elif input_unit_lower == 'kelvin':
        celsius_value = value - 273.15
    else: # input_unit is celsius
        celsius_value = value

    # Convert from Celsius to the desired output unit
    if output_unit_lower == 'fahrenheit':
        converted_value = (celsius_value * 9/5) + 32
    elif output_unit_lower == 'kelvin':
        converted_value = celsius_value + 273.15
    else: # output_unit is celsius
        converted_value = celsius_value

    return converted_value

# Example Usage:
print("--- Example Conversions ---")
print(f"30°C to Fahrenheit: {convert_temperature_advanced(30, 'Celsius', 'Fahrenheit')}°F")
print(f"86°F to Celsius: {convert_temperature_advanced(86, 'Fahrenheit', 'Celsius')}°C")
print(f"0°C to Kelvin: {convert_temperature_advanced(0, 'Celsius', 'Kelvin')}K")
print(f"273.15K to Celsius: {convert_temperature_advanced(273.15, 'Kelvin', 'Celsius')}°C")
print(f"68°F to Kelvin: {convert_temperature_advanced(68, 'Fahrenheit', 'Kelvin')}K")
print(f"300K to Fahrenheit: {convert_temperature_advanced(300, 'Kelvin', 'Fahrenheit')}°F")

print("\n--- Example Error Handling ---")
print("Invalid temperature value:")
convert_temperature_advanced("abc", 'Celsius', 'Fahrenheit')
print("\nInvalid input unit:")
convert_temperature_advanced(25, 'Centigrade', 'Fahrenheit')
print("\nInvalid output unit:")
convert_temperature_advanced(77, 'Fahrenheit', 'Rankine')

--- Example Conversions ---
30°C to Fahrenheit: 86.0°F
86°F to Celsius: 30.0°C
0°C to Kelvin: 273.15K
273.15K to Celsius: 0.0°C
68°F to Kelvin: 293.15K
300K to Fahrenheit: 80.33000000000004°F

--- Example Error Handling ---
Invalid temperature value:
Error: Invalid temperature value 'abc'. Input value must be numeric.

Invalid input unit:
Error: Invalid input unit 'Centigrade'. Valid units are: celsius, fahrenheit, kelvin.

Invalid output unit:
Error: Invalid output unit 'Rankine'. Valid units are: celsius, fahrenheit, kelvin.


**Reasoning**:
Explain the functionality of the code generated from the second refined prompt, detailing its inputs, calculation logic, validation, and improvements over the previous versions, as per the instructions.



In [16]:
# Explanation of the functionality of the code generated from the second refined prompt
# and how it addresses more complex scenarios.

print("Explanation of the `convert_temperature_advanced` function:")

print("\n1. Addressing Complex Scenarios:")
print("The second refined prompt significantly increased the complexity required by asking for conversions between three different units (Celsius, Fahrenheit, Kelvin) and demanding robust error handling.")
print("This led to the generation of the `convert_temperature_advanced` function, which is much more versatile and resilient than the previous single-conversion functions.")
print("It models a more realistic scenario where a user might need to convert temperatures between various common scales and where invalid inputs should be handled gracefully.")

print("\n2. Inputs of the `convert_temperature_advanced` function:")
print("This function requires three specific inputs:")
print("  - `value`: The numerical temperature value to be converted.")
print("  - `input_unit`: A string specifying the unit of the `value`. Expected inputs are 'Celsius', 'Fahrenheit', or 'Kelvin'.")
print("  - `output_unit`: A string specifying the desired unit for the converted temperature. Expected inputs are 'Celsius', 'Fahrenheit', or 'Kelvin'.")

print("\n3. Step-by-Step Calculation Logic:")
print("The function performs the conversion using the following steps:")
print("  - **Input Validation:** It first checks if the `value` is numeric and if the `input_unit` and `output_unit` are among the valid options. If any validation fails, it prints an error and returns `None`.")
print("  - **Normalization to Celsius:** To simplify the conversion logic, the input temperature is first converted to Celsius, regardless of the original `input_unit`. Standard formulas are used for Fahrenheit to Celsius and Kelvin to Celsius.")
print("  - **Conversion to Output Unit:** The temperature value (now in Celsius) is then converted to the `output_unit` using the appropriate standard formula (Celsius to Fahrenheit or Celsius to Kelvin). If the `output_unit` is Celsius, no further conversion is needed.")
print("  - **Return Value:** The function returns the final converted temperature value as a float.")

print("\n4. Robust Error Handling:")
print("A key improvement in this version is the comprehensive error handling:")
print("  - It explicitly checks for non-numeric `value` input.")
print("  - It validates both the `input_unit` and `output_unit` strings against a list of accepted units.")
print("  - In case of any invalid input or unit, it prints a clear, informative error message indicating what went wrong.")
print("  - It returns `None` upon error, which is a standard Pythonic way to indicate failure or the absence of a valid result, allowing the calling code to check for errors.")

print("\n5. Improvements over Previous Versions:")
print("The `convert_temperature_advanced` function is a significant leap forward from the previous versions:")
print("  - **Multi-Unit Support:** Unlike the previous functions that only handled one specific conversion (or assumed one), this function supports conversions between all three specified units.")
print("  - **Increased Flexibility:** A single function can now handle multiple conversion types based on the provided inputs.")
print("  - **Enhanced Robustness:** The inclusion of explicit error handling for invalid values and units makes the function much more reliable and user-friendly, preventing unexpected crashes due to bad input.")
print("This demonstrates how adding requirements for multiple functionalities and robust error handling in the prompt leads to the generation of more complex, flexible, and resilient code.")

Explanation of the `convert_temperature_advanced` function:

1. Addressing Complex Scenarios:
The second refined prompt significantly increased the complexity required by asking for conversions between three different units (Celsius, Fahrenheit, Kelvin) and demanding robust error handling.
This led to the generation of the `convert_temperature_advanced` function, which is much more versatile and resilient than the previous single-conversion functions.
It models a more realistic scenario where a user might need to convert temperatures between various common scales and where invalid inputs should be handled gracefully.

2. Inputs of the `convert_temperature_advanced` function:
This function requires three specific inputs:
  - `value`: The numerical temperature value to be converted.
  - `input_unit`: A string specifying the unit of the `value`. Expected inputs are 'Celsius', 'Fahrenheit', or 'Kelvin'.
  - `output_unit`: A string specifying the desired unit for the converted temperature. 

## Summary:

### Data Analysis Key Findings

*   Starting with a vague prompt ("Generate a Python function for temperature conversion") resulted in a basic function that assumed Celsius to Fahrenheit conversion, lacked input validation, and was inflexible.
*   Refining the prompt to specify a single conversion ("Generate a Python function to convert Celsius to Fahrenheit") led to a function tailored for that specific conversion, including the correct formula, and introduced basic input validation.
*   Further refining the prompt to include multiple units (Celsius, Fahrenheit, Kelvin) and error handling resulted in a more complex and versatile function (`convert_temperature_advanced`) capable of handling conversions between the three specified units and providing robust error handling for invalid inputs or units.
*   The generated code structure in the advanced version uses an intermediate unit (Celsius) to simplify the conversion logic between multiple scales and includes explicit checks for non-numeric values and invalid unit strings.

### Insights or Next Steps

*   Prompt specificity is crucial for generating code that precisely meets requirements, handles complex scenarios, and includes features like error handling.
*   For more complex tasks, breaking down requirements (like multi-unit support and error handling) into clear instructions within the prompt is essential for generating robust and versatile code.
